// Package orphans implements the "find_orphans" MCP tool, which
// surfaces orphan symbols — code that nothing references — from an Enola
// architectural snapshot, so users can pinpoint dead code to remove.
//
// Engine-boundary note: this package knows nothing about the engine. Register
// takes an accessor that yields the store the latest snapshot published, because
// a tool handler runs per call and must not be pinned to the store that existed
// when it was registered; ExplainSection takes a store outright, because it runs
// once, straight after a snapshot. Keeping the engine out is what lets this code
// live either side of the module boundary.
//
// Detection caveat: the snapshot graph stores call/implements edges as
// UNRESOLVED short names (e.g. "handleError", "json.NewDecoder",
// "HandlerV2.Create") while symbol facts carry canonical names (e.g.
// "internal/app/user.HandlerV2.Create"). Exact-name reverse lookups therefore
// match almost nothing. We instead match references by short name with a
// deliberately conservative bias: a symbol counts as USED if any reference
// matches one of its short forms. This errs toward not flagging, so we never
// recommend deleting live code (cost: some real orphans with common names are
// missed). Type usage (a struct used only as a field/param/return type) is not
// an edge in the snapshot at all, so struct/type findings are tagged
// lower-confidence.
package orphans

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"unicode"

	"github.com/enola-labs/enola/internal/explainers/deadmethods"
	"github.com/enola-labs/enola/internal/facts"
	"github.com/enola-labs/enola/pkg/mcputil"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// Prop keys are the extractors' own string keys, which internal/facts does not
// export as constants. Fact-kind, relation, and symbol-kind values come from it
// (facts.Kind*, facts.Rel*, facts.Symbol*).
const (
	propSymbolKind = "symbol_kind"
	propExported   = "exported"
	// propOverride: symbol fact (Kotlin/Swift) → the declaration is an `override`,
	// dispatched polymorphically through its supertype and never referenced by its
	// own literal name (framework lifecycle callbacks, interface implementations).
	propOverride = "override"
	// propDIProvider: symbol fact (Kotlin) → a Dagger/Hilt @Provides/@Binds method,
	// invoked reflectively by the DI container, never by name.
	propDIProvider = "di_provider"
	// propAndroidComponent: symbol fact (Kotlin) → the Android component role
	// (activity, fragment, service, composable, …). The manifest/runtime-instantiated
	// roles are entry points with no in-code caller by construction.
	propAndroidComponent = "android_component"
	// propIOSComponent: symbol fact (Swift) → the iOS component role (swiftui_app,
	// swiftui_view, viewcontroller, viewmodel, …). Only the runtime-instantiated
	// role is an entry point; the rest are constructed by app code and their edges
	// are tracked. See iosEntryPointComponents.
	propIOSComponent = "ios_component"
	propHandler      = "handler" // route fact → its handler symbol (e.g. "h.GetByCode")
	// propWebComponent: symbol fact (TS/JS) → the React/Vue role (component, hook,
	// route_handler, composable). Rendered via JSX, wired by a data-driven route
	// table, or dispatched by the framework — usage that is only partially captured
	// as edges — so a TS/JS orphan of this shape is a lead to verify, not a certainty.
	propWebComponent = "web_component"
	// propLanguage: symbol fact → the source language ("typescript" for both TS & JS).
	// Confidence is language-aware: TS/JS usage (JSX, dynamic import, string dispatch)
	// is less completely edge-tracked than a plain Go/Rust call graph.
	propLanguage  = "language"
	propReexports = "reexports" // dependency fact (Python __init__.py) → re-exported short names
	// propCLICommand: symbol fact (Python) → a click/Typer CLI command or group
	// (@cli.command, @app.group). Registered with and dispatched by the CLI
	// framework, never called by name — an entry point, not dead code.
	propCLICommand = "cli_command"
	// propFrameworkRegistered: symbol fact (Python) → registered with a framework by
	// a decorator (FastAPI @app.exception_handler/@app.middleware/@app.on_event,
	// Modal @app.function/@app.local_entrypoint). The framework invokes it on a
	// matching event; nothing calls it by name, so it has no incoming call edge by
	// construction — an entry point, not dead code.
	propFrameworkRegistered = "framework_registered"
	// propGenerated: any fact → came from a file carrying a codegen banner
	// ("DO NOT EDIT", "generated by", …). A generator emits a whole API surface
	// whether or not the project uses all of it, and the unused half is not a
	// cleanup opportunity: deleting it just means regenerating it.
	propGenerated = "generated"
	// propSpringComponent: symbol fact (Java/Kotlin) → the Spring stereotype role
	// (a non-empty string: component/service/repository/controller/configuration).
	// The class is instantiated and wired by the Spring container via classpath
	// scanning, never referenced by its own name in code, so an unreferenced one is
	// an entry point, not dead code. (Dagger @Component interfaces carry di_component,
	// not this prop, so they are unaffected.)
	propSpringComponent = "component"
	// propDubboActivate: symbol fact (Java) → an Apache Dubbo @Activate SPI extension.
	// Instantiated by name by Dubbo's ExtensionLoader from a META-INF/dubbo service
	// file, never referenced in code — an entry point, not dead code.
	propDubboActivate = "dubbo_activate"
	// propScannedPlugin: symbol fact (Java) → a class discovered by runtime classpath
	// scanning for a plugin annotation (ThingsBoard @RuleNode). Instantiated by the
	// framework, never referenced by its own name — an entry point, not dead code.
	// (Dubbo SPI impls registered only in a META-INF service file are rescued instead
	// by a KindFileRef reference the Java extractor now emits, not by this prop.)
	propScannedPlugin = "scanned_plugin"
	// propDynamicSendPrefixes: file-scope fact → static prefixes of interpolated
	// dispatch symbols (`:"report_#{type}"` → "report_"). Methods with these prefixes
	// are invoked by computed name (public_send/send) and have no call edge.
	propDynamicSendPrefixes = "dynamic_send_prefixes"
)

// Orphan classes.
const (
	classIsolated     = "isolated"     // no references in OR out
	classUnreferenced = "unreferenced" // no references in, but references others
)

// Confidence tiers.
const (
	confHigh   = "high"   // plain calls: incoming usage reliably captured as edges
	confMedium = "medium" // struct/class/interface: instantiate/inject/implement edges ARE tracked, so an orphan is a strong (but not certain — type usage isn't tracked) dead-code lead
	confLow    = "low"    // method/type/const/var: usage is not edge-tracked
)

// UsageTracked reports whether this orphan's kind has its incoming usage reliably
// captured as edges — i.e. we can actually tell whether it is used. True for the
// high (function calls) and medium (class/interface instantiate/inject/implement)
// tiers; false only for the low tier, whose usage is NOT edge-tracked (methods,
// types, consts, vars), so a "low" orphan is a weak lead rather than a real
// finding. Consumers that must not raise false positives should count only
// UsageTracked orphans.
func (o Orphan) UsageTracked() bool { return o.Confidence != confLow }

// isUsageKind reports whether a relation kind represents a real symbol→symbol
// usage edge (as opposed to the structural "declares" or module-level "imports").
func isUsageKind(kind string) bool {
	switch kind {
	case facts.RelCalls, facts.RelImplements, facts.RelInstantiates, facts.RelInjects:
		return true
	}
	return false
}

// symInput is the per-symbol input to the pure classifier.
type symInput struct {
	Name     string
	Kind     string // symbol_kind: function, method, struct, interface, type, class, constant, variable
	File     string
	Line     int
	Repo     string
	Package  string // declaring module (the declares-relation target)
	Exported bool
	UsageOut bool // has at least one outgoing usage edge
	// Claimed records that the dead-methods explainer already reports this method.
	// That explainer asks the narrower question it can answer on Ruby, scoped to the
	// surfaces whose callers the graph can actually see, and leaves out the ones
	// where a name index reads wrong (models, controllers, views, serializers).
	// Where both can see a method, the scoped answer is the one worth reporting.
	Claimed bool
	// Framework/DI entry points: reached by the runtime/container via dispatch, not
	// by a call edge, so an absent incoming reference does not mean dead code.
	Override         bool   // an `override` — dispatched through its supertype
	DIProvider       bool   // a Dagger/Hilt @Provides/@Binds method
	AndroidComponent string // android_component role (activity, fragment, composable, …)
	IOSComponent     string // ios_component role (swiftui_app, swiftui_view, viewcontroller, …)
	WebComponent     string // web_component role (component, hook, route_handler, composable)
	Language         string // source language ("typescript" covers TS & JS)
	CLICommand       bool   // Python click/Typer CLI command/group — framework-dispatched
	FrameworkReg     bool   // Python decorator-registered handler (FastAPI/Modal) — framework-invoked
	Generated        bool   // declared in codegen output — unused surface is not a cleanup target
	SpringComponent  string // Spring stereotype role (component/service/…) — container-instantiated
	DubboActivate    bool   // Apache Dubbo @Activate SPI extension — ExtensionLoader-instantiated
	ScannedPlugin    bool   // classpath-scanned plugin class (e.g. ThingsBoard @RuleNode)
}

// Orphan is a single reported orphan symbol.
type Orphan struct {
	Name       string `json:"name"`
	Kind       string `json:"kind"`
	Class      string `json:"class"`      // isolated | unreferenced
	Confidence string `json:"confidence"` // high | medium | low
	Package    string `json:"package,omitempty"`
	File       string `json:"file,omitempty"`
	Line       int    `json:"line,omitempty"`
	Repo       string `json:"repo,omitempty"`
	Exported   bool   `json:"exported"`
	Note       string `json:"note,omitempty"`
}

// options carries the resolved (defaulted) tool arguments into the pure core.
type options struct {
	Mode               string // both | isolated | unreferenced
	Kind               string
	Package            string
	Repo               string
	Visibility         string // all | exported | unexported
	Confidence         string // "" (all) | high | low
	IncludeTests       bool
	IncludeEntrypoints bool
}

// isTestPath reports whether a repo-relative file path is test or test-support
// code (test trees, and the mocks/fixtures/helpers that exist only to serve them).
// This matters because test files are excluded from the snapshot by config ignore,
// so the tests that consume a mock or helper aren't in the graph — without the
// exclusion, such test-support code is mis-reported as dead because its only
// callers are invisible.
//
// The rule itself lives in the OSS module (facts.IsTestPath). It used to be a local
// copy, one of three that had drifted apart in both directions — this one was
// missing `Tests`/`Mocks`/`__tests__` (1959 false orphans on nan/nebenan-iOS, 34.5%
// of every orphan the repo reported) while perf's copy was missing the Gradle/KMP
// source sets, and the OSS god-class/hotspots explainers had no path check at all.
//
// Two of this copy's own rules were fixed/28 defects and did NOT survive the merge:
// `strings.Contains(p, "_test.")` claimed the production ActiveJob
// `finish_kindness_reminder_ab_test.rb`, and an unqualified `test_` prefix claimed
// `app/jobs/test_job.rb` and superset's `superset/cli/test_db.py`. Real Ruby and
// Python tests live in a `spec/`/`test/`/`tests/` tree, which the segment rules
// already claim, so those two rules only ever removed production code from the
// analysis. See internal/facts/testpath.go for the measurements.
func isTestPath(p string) bool { return facts.IsTestPath(p) }

// isDunder reports whether a bare name is a Python dunder (e.g. "__init__",
// "__enter__"). Dunders are invoked implicitly by the runtime, never referenced
// by name, so they must not be reported as orphans.
func isDunder(bareName string) bool {
	return len(bareName) > 4 &&
		strings.HasPrefix(bareName, "__") && strings.HasSuffix(bareName, "__")
}

// lastSeg returns the substring after the final name separator ('.' or '#').
// "json.NewDecoder" → "NewDecoder"; "handleError" → "handleError";
// "PostsController#markdown_id" → "markdown_id" (Ruby instance methods).
func lastSeg(s string) string {
	if i := strings.LastIndexAny(s, ".#"); i >= 0 {
		return s[i+1:]
	}
	return s
}

// candidateNames returns the short forms a symbol may be referenced by. The
// canonical name has the form "<pkg/dir>.<Sym>" or "<pkg/dir>.<Recv>.<Method>";
// the package directory uses '/' separators and attaches the symbol with '.'.
// Ruby instance methods use '#' as the receiver/method separator
// ("PostsController#markdown_id"), so both '.' and '#' are treated as name
// separators. Methods yield {Method, Recv.Method}; everything else yields {Sym}.
func candidateNames(name, kind string) []string {
	tail := name
	if i := strings.LastIndex(tail, "/"); i >= 0 {
		tail = tail[i+1:]
	}
	parts := strings.FieldsFunc(tail, func(r rune) bool { return r == '.' || r == '#' })
	n := len(parts)
	if n == 0 {
		return nil
	}
	// Strip a leading "::" — a top-level reopened class is named "::Post" but is
	// referenced as the bare "Post".
	final := strings.TrimPrefix(parts[n-1], "::")
	if final == "" {
		return nil
	}
	var out []string
	if kind == facts.SymbolMethod && n >= 2 {
		out = []string{final, strings.TrimPrefix(parts[n-2], "::") + "." + final}
	} else {
		out = []string{final}
	}
	// Ruby constants nest with "::"; a reference from inside the enclosing module
	// uses the short (last) segment, so match "AdPlugin::HouseAdSerializer" against
	// a bare "HouseAdSerializer" too. Other languages carry no "::", so this is a
	// no-op for them.
	if i := strings.LastIndex(final, "::"); i >= 0 {
		if seg := final[i+2:]; seg != "" {
			out = append(out, seg)
		}
	}
	// Ruby setters: `def foo=` yields the symbol "…foo=", but a call site `x.foo = v`
	// records the method as "foo" (no "="). Match the setter against that bare form
	// (and the "Recv.foo" form) so a setter used only via assignment is not mis-reported
	// as dead. Conservative: this only ADDS candidates, so it can never create a false
	// orphan (worst case, a getter call also keeps the same-named setter alive).
	if base, ok := strings.CutSuffix(final, "="); ok && base != "" {
		out = append(out, base)
		if kind == facts.SymbolMethod && n >= 2 {
			out = append(out, strings.TrimPrefix(parts[n-2], "::")+"."+base)
		}
	}
	return out
}

// bareName returns a symbol's unqualified name (its final '.'-segment).
func bareName(name string) string { return lastSeg(name) }

// referencedByOther reports whether any source other than the symbol itself
// references one of the symbol's short forms. Self-references (e.g. recursion)
// do not count as use.
func referencedByOther(sym symInput, refSources refIndex) bool {
	for _, cand := range candidateNames(sym.Name, sym.Kind) {
		if refSources[cand].referenced(sym.Name) {
			return true
		}
	}
	return false
}

// isDataMemberKind reports whether a kind is a data member (struct/union field,
// package-level variable or constant). Their usage — field reads and variable
// references — is never emitted as a graph edge by any extractor, so every one
// would be flagged as an orphan (a ~100% false-positive rate that, on large C
// codebases like the Linux kernel, swamps the real dead-code signal with hundreds
// of thousands of struct fields). They are excluded from the default analysis but
// remain reachable via an explicit kind= filter.
func isDataMemberKind(kind string) bool {
	return kind == facts.SymbolVariable || kind == facts.SymbolConstant
}

// frameworkLoadedSegments mark directory trees that are not shippable application
// code we would ever flag as dead. Their symbols are unreferenced-by-name by
// construction, so each would be a false positive — pure noise in the aggregate,
// exactly like test trees:
//   - migrate / post_migrate: Rails migrations, run once by ActiveRecord by
//     filename and never referenced by name (the single largest dead-code-noise
//     bucket on a Rails app like Discourse — thousands of one-shot classes).
//   - script: standalone scripts / one-off entry points, invoked directly.
//   - vendor: vendored third-party code, not ours to clean up (and only partially
//     covered by the OSS generated-path filter).
//
// They are dropped from the default analysis but stay reachable via an explicit
// package= filter (mirrors the data-member kind= opt-in).
var frameworkLoadedSegments = map[string]bool{
	"migrate": true, "post_migrate": true, // Rails db/migrate, db/post_migrate
	"script": true, "scripts": true,
	"vendor": true,
}

// isFrameworkLoadedPath reports whether a repo-relative file path is in a
// framework-loaded / non-app tree (see frameworkLoadedSegments).
func isFrameworkLoadedPath(p string) bool {
	for _, part := range strings.Split(p, "/") {
		if frameworkLoadedSegments[part] {
			return true
		}
	}
	return false
}

// isScopePseudoSymbol reports whether a symbol name is a Rails model `scope:<name>`
// pseudo-symbol. The Ruby extractor emits each `scope :foo` as a receiver-less
// `scope:foo` symbol, but scopes are invoked via dynamic class-method dispatch
// (Model.foo, chained), never by that literal name — so, like dunders, they can
// never match a reference and would always be (falsely) reported, polluting the
// high-confidence bucket. Excluded unconditionally.
func isScopePseudoSymbol(name string) bool {
	return strings.HasPrefix(name, "scope:")
}

// rubyImplicitHooks are Ruby class/module/object lifecycle callbacks invoked
// implicitly by the runtime (never by an explicit by-name call): the interpreter
// calls `inherited` when a class is subclassed, `included`/`extended`/`prepended`
// when a module is mixed in, `method_missing`/`respond_to_missing?` on dispatch,
// `initialize` via `.new`, and so on. Like Python dunders they can never match a
// reference and would always be (falsely) reported. Excluded for Ruby symbols.
var rubyImplicitHooks = map[string]bool{
	"inherited": true, "included": true, "extended": true, "prepended": true,
	"method_missing": true, "respond_to_missing?": true,
	"method_added": true, "method_removed": true, "method_undefined": true,
	"singleton_method_added": true, "singleton_method_removed": true, "singleton_method_undefined": true,
	"const_missing": true, "append_features": true, "prepend_features": true, "extend_object": true,
	"initialize": true, "initialize_copy": true, "initialize_dup": true, "initialize_clone": true,
	"coerce": true, "to_proc": true,
}

// rubyFrameworkHooks are convention methods that popular Ruby frameworks invoke by
// reflection on classes that define/override them — never by an explicit call in
// app code, so they carry no call edge and would always be (falsely) reported.
// Unlike the language-level rubyImplicitHooks these are library conventions; the
// list is intentionally curated (specific, low-collision names) and extensible.
var rubyFrameworkHooks = map[string]bool{
	// GraphQL-Ruby: the gem calls these on schema/type/field/mutation/resolver classes.
	"authorized?": true, "authorizes_object?": true,
	"unauthorized_object": true, "unauthorized_field": true,
	"visible?": true, "accessible?": true,
	"coerce_input": true, "coerce_result": true, "scope_items": true,
	// ActionCable channels.
	"subscribed": true, "unsubscribed": true,
	// Rails AbstractController reflection.
	"action_methods": true,
	// Rails ActiveRecord single-table-inheritance reflection (invoked by the ORM).
	"find_sti_class": true, "sti_class_for": true, "sti_name": true,
	"polymorphic_name": true, "discriminate_class_for_record": true,
}

// isRubyImplicitHook reports whether a Ruby (.rb) symbol's bare name is a runtime
// lifecycle hook (rubyImplicitHooks) or a framework-invoked convention method
// (rubyFrameworkHooks). Gated on the file extension so identically named methods in
// other languages are unaffected.
func isRubyImplicitHook(file, bareName string) bool {
	return strings.HasSuffix(file, ".rb") && (rubyImplicitHooks[bareName] || rubyFrameworkHooks[bareName])
}

// constReceiverRefs returns the constant-receiver short forms implied by a
// "Recv.method" usage target. Extractors record a call on a constant as
// "Foo.bar" / "Ns::Class.method"; the receiver constant ("Foo", "Ns::Class") is
// itself used, but that use never appears as a standalone edge — so a class
// referenced only as a call receiver (e.g. Ruby `PostCreator.create`, with no
// instantiates edge) looks unreferenced. We fold the receiver in as a use. Only
// uppercase-initial receivers (constants/types) qualify, so lowercase variable
// receivers and package qualifiers (Go `json.NewDecoder`) are not mistaken for a
// class reference. This only ever ADDS references, so it can never turn live code
// into a false orphan — consistent with the package's conservative bias.
func constReceiverRefs(target string) []string {
	i := strings.LastIndex(target, ".")
	if i <= 0 {
		return nil
	}
	recv := target[:i]
	if r := rune(recv[0]); r < 'A' || r > 'Z' {
		return nil
	}
	out := []string{recv}
	if j := strings.LastIndex(recv, "::"); j >= 0 {
		if tail := recv[j+2:]; tail != "" {
			out = append(out, tail)
		}
	}
	return out
}

// selfReceiverRefs returns the bare method name implied by a self-qualified usage
// target. Extractors normally reduce same-object dispatch to a bare method name,
// but as a defense in depth (across languages) we also fold any target shaped
// `self.X`, `self.class.X`, `cls.X`, `this.X`, or `self::X` down to `X` — so a
// method reached only via such a dynamic self-dispatch is not mis-reported as an
// unreferenced orphan. Like constReceiverRefs this only ever ADDS references, so
// it can never turn live code into a false orphan.
func selfReceiverRefs(target string) []string {
	var recv, method string
	if i := strings.LastIndex(target, "."); i > 0 && i < len(target)-1 {
		recv, method = target[:i], target[i+1:]
	} else if i := strings.LastIndex(target, "::"); i > 0 && i < len(target)-2 {
		recv, method = target[:i], target[i+2:]
	} else {
		return nil
	}
	switch recv {
	case "self", "self.class", "self.singleton_class", "cls", "this", "klass":
		return []string{method}
	}
	return nil
}

// androidEntryPointComponents are Android component roles instantiated by the
// framework/runtime (via the manifest, the Compose runtime, WorkManager, or a
// ViewModelProvider) rather than by app code — so they have no incoming call edge
// by construction and must not be reported as orphans, like main/init. Roles that
// ARE ordinary app classes reached through DI (repository, usecase, di_module) are
// deliberately omitted so a genuinely dead one is still surfaced.
var androidEntryPointComponents = map[string]bool{
	"application": true, "activity": true, "fragment": true, "service": true,
	"broadcast_receiver": true, "content_provider": true, "worker": true,
	"composable": true, "viewmodel": true,
}

// iosEntryPointComponents are iOS component roles instantiated by the SwiftUI
// runtime rather than by app code, so they have no incoming call edge by
// construction — like main/init. The Android set above is deliberately NOT
// mirrored: app code constructs a SwiftUI View from its parent's body, a ViewModel
// via @StateObject, and a UIViewController from a coordinator, and those edges ARE
// tracked, so an unreferenced one is real dead code. Measured across
// my-golf-journal-ios and nebenan-iOS: 0 of 25 viewcontroller symbols are orphans,
// and each of the 6 uiview orphans is genuinely unused — rescuing either role would
// suppress real findings to fix nothing.
var iosEntryPointComponents = map[string]bool{
	"swiftui_app": true,
}

// isExcluded reports whether a symbol is dropped before orphan analysis given
// the test/entry-point options.
func isExcluded(sym symInput, opts options) bool {
	bn := bareName(sym.Name)
	// Dunders (__init__, __enter__, …) are invoked implicitly, never by name.
	if isDunder(bn) {
		return true
	}
	// Rails model scopes are dynamic-dispatch pseudo-symbols, never referenced by
	// the literal `scope:<name>` — always noise, like dunders.
	if isScopePseudoSymbol(sym.Name) {
		return true
	}
	// Ruby lifecycle hooks (inherited/included/method_missing/initialize/…) are
	// invoked by the runtime, never by name — always noise, like dunders.
	if isRubyImplicitHook(sym.File, bn) {
		return true
	}
	// Data members have no edge-tracked usage, so they are pure noise in the
	// aggregate view. Drop them unless the caller explicitly asks for that kind.
	if opts.Kind == "" && isDataMemberKind(sym.Kind) {
		return true
	}
	// Framework-loaded / non-app trees (Rails migrations, script/, vendor/) are
	// unreferenced-by-name by construction. Drop them unless the caller has scoped
	// the query to a package (the explicit opt-in to inspect such a tree).
	if opts.Package == "" && isFrameworkLoadedPath(sym.File) {
		return true
	}
	// TS/JS CLI-task trees (e.g. `tasks/`) are dispatched by dynamic-string require
	// (`require(`./tasks/${name}`)`) from a runner, so their entry functions have no
	// resolvable caller — like script/ above. Language-gated so a Go `internal/tasks`
	// package is unaffected; opt back in with package=.
	if opts.Package == "" && isTSLang(sym.Language) && isTSDynamicEntryPath(sym.File) {
		return true
	}
	// Python documentation trees (docs/ — Sphinx conf.py, diagram generators) are
	// run by the docs toolchain, never imported by the app, so their functions have
	// no caller by construction. Language-gated so a non-Python `docs` package is
	// unaffected; opt back in with package=.
	if opts.Package == "" && isPyLang(sym.Language) && isPyNonAppPath(sym.File) {
		return true
	}
	// Codegen output (file carries a "DO NOT EDIT"/"generated by" banner). A
	// generator emits a whole API surface regardless of how much the project calls,
	// so its unreferenced half is guaranteed noise: deleting it does not clean
	// anything up, it just gets regenerated. Language-agnostic — the banner is the
	// signal — and reachable with package= like the trees above.
	if opts.Package == "" && sym.Generated {
		return true
	}
	if !opts.IncludeTests {
		if isTestPath(sym.File) {
			return true
		}
		// Go test/benchmark/example/fuzz entry points and pytest test_* functions.
		if strings.HasPrefix(bn, "Test") || strings.HasPrefix(bn, "Benchmark") ||
			strings.HasPrefix(bn, "Example") || strings.HasPrefix(bn, "Fuzz") ||
			strings.HasPrefix(bn, "test_") {
			return true
		}
	}
	if !opts.IncludeEntrypoints {
		if bn == "main" || bn == "init" {
			return true
		}
		// Framework/DI entry points (Kotlin `override` callbacks — Android lifecycle,
		// interface implementations — Dagger/Hilt @Provides/@Binds methods,
		// manifest/runtime-instantiated Android components: Activities, Fragments,
		// Services, Workers, Composables, …, and the @main SwiftUI App) are dispatched
		// by the runtime/container, never referenced by their own literal name, so they
		// have no incoming call edge by construction. Like main/init, they are not dead
		// code; treat them as entry points and drop them unless the caller opts in.
		// (An override also cannot be deleted in isolation.)
		if sym.Override || sym.DIProvider || androidEntryPointComponents[sym.AndroidComponent] ||
			iosEntryPointComponents[sym.IOSComponent] {
			return true
		}
		// JVM framework-instantiated classes: a Spring stereotype (@Component/@Service/
		// @Configuration/… — a non-empty `component` role) is wired by the Spring
		// container via classpath scanning, and a Dubbo @Activate SPI extension is
		// instantiated by name by the ExtensionLoader from a META-INF/dubbo service
		// file. Neither is referenced by its own name in code, so an unreferenced one
		// has no incoming edge by construction — an entry point, not dead code. (A
		// genuinely-dead bean — defined but never scanned — is thereby also hidden;
		// that is the standard entry-point tradeoff, matching the Android/iOS/route
		// cases above. The untagged plain-SPI impls — registered only in a service
		// file, no @Activate — carry neither prop and are still reported.)
		if sym.SpringComponent != "" || sym.DubboActivate || sym.ScannedPlugin {
			return true
		}
		// Next.js App-Router route handlers (GET/POST/… exports in a route.ts) are
		// invoked by the framework for a matching request, never referenced by name —
		// an entry point like main, not dead code. React components/hooks are NOT
		// excluded here: a genuinely-unreferenced component IS dead code we want
		// surfaced (just at a lower, verify-first confidence — see confidenceFor).
		if sym.WebComponent == "route_handler" {
			return true
		}
		// React class-component lifecycle methods (render, componentDidMount, …) are
		// called by React itself, never by name, so they have no incoming call edge by
		// construction — like Android lifecycle overrides. They dominate the TS/JS
		// method-orphan noise; treat them as framework entry points and drop them
		// unless the caller opts in.
		if sym.Kind == facts.SymbolMethod && isTSLang(sym.Language) && reactLifecycleMethods[bn] {
			return true
		}
		// Python framework hooks (gunicorn server hooks, ASGI lifespan, Airflow
		// cluster policies / settings hooks) are dispatched by name from config or a
		// settings module, never by a static call — entry points, not dead code.
		if isPyLang(sym.Language) && pyFrameworkHookNames[bn] {
			return true
		}
		// click/Typer CLI commands are registered with and dispatched by the CLI
		// framework, never called by name — entry points like main.
		if sym.CLICommand {
			return true
		}
		// Decorator-registered handlers (FastAPI exception handlers/middleware/event
		// hooks, Modal remote functions) are invoked by the framework on a matching
		// event, never by a static call — the same case as the CLI commands above.
		if sym.FrameworkReg {
			return true
		}
	}
	return false
}

// reactLifecycleMethods are React class-component lifecycle methods invoked by the
// React runtime (mount/update/unmount/error phases), never referenced by their own
// name. Includes the legacy and UNSAFE_-prefixed variants and the two static
// getDerived* hooks. `render` is included: on a class in a React/TS codebase it is a
// component's render method, and an unreferenced one is framework-dispatched noise.
var reactLifecycleMethods = map[string]bool{
	"render":                           true,
	"componentDidMount":                true,
	"componentDidUpdate":               true,
	"componentWillUnmount":             true,
	"componentDidCatch":                true,
	"shouldComponentUpdate":            true,
	"getSnapshotBeforeUpdate":          true,
	"getDerivedStateFromProps":         true,
	"getDerivedStateFromError":         true,
	"componentWillMount":               true,
	"componentWillReceiveProps":        true,
	"componentWillUpdate":              true,
	"UNSAFE_componentWillMount":        true,
	"UNSAFE_componentWillReceiveProps": true,
	"UNSAFE_componentWillUpdate":       true,
}

// tsDynamicEntrySegments are path segments of TS/JS trees whose modules are loaded by
// a dynamic-string require/import from a CLI runner rather than a static import, so
// their entry functions have no resolvable caller (like script/ for Ruby/Rails).
var tsDynamicEntrySegments = map[string]bool{
	"tasks": true,
}

// isTSDynamicEntryPath reports whether a repo-relative path is in a TS/JS
// dynamic-entry tree (see tsDynamicEntrySegments).
func isTSDynamicEntryPath(p string) bool {
	for _, part := range strings.Split(p, "/") {
		if tsDynamicEntrySegments[part] {
			return true
		}
	}
	return false
}

// isPyLang reports whether the source language is Python.
func isPyLang(lang string) bool { return lang == "python" }

// pyNonAppSegments mark Python directory trees that are not shippable application
// code: documentation builders (Sphinx conf.py, docs/img/* diagram generators) are
// run by the docs toolchain, never imported by the app, so their functions have no
// call edge by construction — pure noise, like script/ for Ruby. Dropped from the
// default analysis but reachable via an explicit package= filter.
var pyNonAppSegments = map[string]bool{
	"docs": true,
	// Sphinx extension modules (loaded by name via setup(app), never imported by the
	// app), example/tutorial DAGs (loaded by the scheduler's DAG-file scan, their task
	// callables dispatched dynamically), and alembic/django migrations (upgrade/
	// downgrade run by filename). All framework-loaded, never called by name.
	"sphinx_exts": true, "example_dags": true, "migrations": true,
	// Performance/benchmark DAG trees — loaded by the scheduler's DAG-file scan like
	// example_dags, their task callables dispatched dynamically.
	"performance_dags": true, "performance_dag": true,
	// Sample programs, evaluation harnesses and benchmark suites. Each is a leaf by
	// construction: a demo's entry function, a benchmark runner and a notebook cell
	// are invoked by a human or a job runner, never by a static call from app code,
	// so every one of them reads as dead. On one real repo these two trees alone were
	// 16 of 92 high-confidence findings — all of them noise. Reachable with package=
	// when you do want to audit them.
	"examples": true, "evals": true, "benchmarks": true, "notebooks": true,
}

// isPyNonAppPath reports whether a repo-relative path is in a Python non-app tree
// (see pyNonAppSegments), or in a top-level `dev/` developer-tooling tree (build/CI
// tooling like Airflow's breeze, registry, and perf scripts — not shipped app code).
// The dev/ check is a top-level-prefix match (not any-segment) so a nested
// `.../dev/...` application package is unaffected.
func isPyNonAppPath(p string) bool {
	if p == "dev" || strings.HasPrefix(p, "dev/") {
		return true
	}
	for _, part := range strings.Split(p, "/") {
		if pyNonAppSegments[part] {
			return true
		}
	}
	return false
}

// pyFrameworkHookNames are Python functions invoked by name by a framework/server
// (loaded from config or a settings module), never by a static call from app code,
// so they have no incoming call edge by construction — entry points like main, not
// dead code. Covers gunicorn server hooks (configured in a gunicorn config module),
// the ASGI/Starlette `lifespan` handler, and Airflow cluster policies / settings
// hooks (imported by name from the local settings module). Dropped unless the caller
// opts in via include_entrypoints.
var pyFrameworkHookNames = map[string]bool{
	// gunicorn server hooks.
	"post_worker_init": true, "worker_exit": true, "on_starting": true,
	"when_ready": true, "pre_fork": true, "post_fork": true, "worker_int": true,
	"pre_exec": true, "pre_request": true, "post_request": true, "child_exit": true,
	"worker_abort": true, "nworkers_changed": true, "on_reload": true, "on_exit": true,
	// ASGI/Starlette lifespan handler.
	"lifespan": true,
	// Airflow cluster policies / settings hooks, loaded by name from local settings.
	"task_policy": true, "dag_policy": true, "task_instance_mutation_hook": true,
	"pod_mutation_hook": true, "get_airflow_context_vars": true,
	"get_dagbag_import_timeout": true,
}

// confidenceFor returns the confidence tier for a symbol. Only plain functions have
// their incoming usage reliably captured by the call graph (high). Methods are
// frequently reached as method values, via interface dispatch, or by reflection —
// none of which are edges — and type usage (field/param/return) is not edge-tracked
// either, so every other kind is low.
func confidenceFor(sym symInput) string {
	name, kind := sym.Name, sym.Kind
	// Operator overloads (Swift `func +`, `func <-`; Ruby `def +`) are invoked via
	// operator syntax, which is largely NOT tracked as a call edge (only custom
	// operators are, in Swift), so an unreferenced one is a lead to verify — never
	// the high-confidence "safest to remove first" tier a plain function would get.
	if isOperatorName(name) {
		return confLow
	}
	// TS/JS usage is only partially edge-tracked: components render via JSX, pages are
	// wired by data-driven route tables, and dynamic import()/require() and string
	// dispatch have no edge. We DO now synthesize file-scope reference edges for those
	// (see the TS extractor's KindFileRef pass), but the coverage is heuristic, so a
	// TS/JS orphan is a lead to verify, never the "safe to delete" high tier a Go/Rust
	// call-graph orphan earns. React components/hooks (web_component set) are the most
	// dynamically-reached, so they drop a further tier.
	if isTSLang(sym.Language) {
		if sym.WebComponent != "" {
			return confLow
		}
		if kind == facts.SymbolFunc {
			return confMedium
		}
		return confLow
	}
	switch kind {
	case facts.SymbolFunc:
		return confHigh
	case facts.SymbolStruct, facts.SymbolClass, facts.SymbolInterface:
		// Types are marked used via instantiates/injects/implements edges, which
		// ARE tracked — so an unreferenced type is a strong dead-code lead. Not
		// high, because field/param/return type usage is not edge-tracked.
		return confMedium
	default:
		return confLow // method, type, const, var
	}
}

// isTSLang reports whether a symbol's language is TypeScript/JavaScript. The TS
// extractor labels both TS and JS facts "typescript".
func isTSLang(lang string) bool {
	switch lang {
	case "typescript", "javascript":
		return true
	}
	return false
}

// isOperatorName reports whether the symbol's short name is an operator (e.g. "+",
// "<-", "^=") rather than an identifier — i.e. its first rune is neither a letter
// nor an underscore.
func isOperatorName(name string) bool {
	seg := lastSeg(name)
	if seg == "" {
		return false
	}
	r := []rune(seg)[0]
	return !unicode.IsLetter(r) && r != '_'
}

// passesFilters applies the kind/package/repo/visibility filters.
func passesFilters(sym symInput, opts options) bool {
	if opts.Kind != "" && sym.Kind != opts.Kind {
		return false
	}
	if opts.Package != "" && !strings.Contains(sym.Package, opts.Package) {
		return false
	}
	if opts.Repo != "" && sym.Repo != opts.Repo {
		return false
	}
	switch opts.Visibility {
	case "exported":
		if !sym.Exported {
			return false
		}
	case "unexported":
		if sym.Exported {
			return false
		}
	}
	switch opts.Confidence {
	case confHigh:
		if confidenceFor(sym) != confHigh {
			return false
		}
	case confMedium:
		if confidenceFor(sym) != confMedium {
			return false
		}
	case confLow:
		if confidenceFor(sym) != confLow {
			return false
		}
	}
	return true
}

// classify is the pure orphan core. Given the symbols, the reference index, and
// resolved options, it returns the orphans matching the requested mode/filters.
// isCandidate reports whether orphan analysis considered this symbol at all: it was
// not excluded (test code, entry points, framework-loaded paths) and it passed the
// caller's filters. This is the ONE admission gate — classify() and population()
// both go through it, so the set of orphans and the population they were drawn from
// can never disagree. Two hand-copied admission tests is precisely how orphans and
// perf drifted apart (see facts.IsTestPath).
//
// It is also the denominator of every rate this tool reports. It used to be
// implicit, and the handler passed len(syms) — every symbol in the snapshot,
// including the test and entry-point symbols that can never be orphans — so the
// dead-code rate was diluted by symbols the analyzer never looked at.
func isCandidate(sym symInput, opts options) bool {
	return !isExcluded(sym, opts) && passesFilters(sym, opts)
}

// population counts the symbols orphan analysis drew from, under the given options.
// It is the honest denominator for len(classify(...)).
func population(syms []symInput, opts options) int {
	n := 0
	for _, sym := range syms {
		if isCandidate(sym, opts) {
			n++
		}
	}
	return n
}

// A symbol is an orphan when nothing else references it; it is classed
// "isolated" when it also references nothing, else "unreferenced".
// Detect returns dead-code orphans in the store using the same collect+classify
// core as the find_orphans tool, with the tool's default options (mode=both, all
// kinds and visibility, tests and entry points excluded). It is what the package's
// own annotate pass runs to mark orphan symbols on the store.
func Detect(store *facts.Store) []Orphan {
	syms, refSources := collect(store)
	orphans := classify(syms, refSources, options{Mode: "both", Visibility: "all"})
	sortOrphans(orphans)
	return orphans
}

func classify(syms []symInput, refSources refIndex, opts options) []Orphan {
	out := make([]Orphan, 0)
	for _, sym := range syms {
		if sym.Claimed {
			continue // dead-methods already reports it; see symInput.Claimed
		}
		if !isCandidate(sym, opts) {
			continue
		}
		if referencedByOther(sym, refSources) {
			continue // referenced → not an orphan
		}
		class := classUnreferenced
		if !sym.UsageOut {
			class = classIsolated
		}
		switch opts.Mode {
		case classIsolated:
			if class != classIsolated {
				continue
			}
		case classUnreferenced:
			if class != classUnreferenced {
				continue
			}
		}
		o := Orphan{
			Name:       sym.Name,
			Kind:       sym.Kind,
			Class:      class,
			Confidence: confidenceFor(sym),
			Package:    sym.Package,
			File:       sym.File,
			Line:       sym.Line,
			Repo:       sym.Repo,
			Exported:   sym.Exported,
		}
		if sym.Exported {
			o.Note = "exported — may be used outside this snapshot; verify before removal"
		}
		out = append(out, o)
	}
	return out
}

// sortOrphans orders orphans by package then name for deterministic output.
func sortOrphans(o []Orphan) {
	sort.SliceStable(o, func(i, j int) bool {
		if o[i].Package != o[j].Package {
			return o[i].Package < o[j].Package
		}
		return o[i].Name < o[j].Name
	})
}

// collect reads the fact store via the public bootstrap API and produces the
// classifier inputs: the per-symbol records and the short-name reference index.
// It never names a facts.* type (module boundary).
func collect(store *facts.Store) ([]symInput, refIndex) {
	claimed := deadmethods.ClaimedSymbols(store)
	symbols := store.ByKind(facts.KindSymbol)
	// References are matched by name (see responseNote), so a symbol's identity is
	// its name. Snapshots can carry several facts for one name (re-exports, the
	// same relative path across repos, extractor quirks); collapse them into one
	// record — UsageOut is OR-ed across copies — so a name is reported at most once
	// and classified consistently rather than as both isolated and unreferenced.
	byName := make(map[string]*symInput, len(symbols))
	order := make([]string, 0, len(symbols))
	refSources := make(refIndex)

	for _, f := range symbols {
		if mcputil.IsGeneratedPath(f.File) {
			continue // build/generated artifact — never a real source orphan
		}
		si := byName[f.Name]
		if si == nil {
			_, isClaimed := claimed[f.Name]
			si = &symInput{Name: f.Name, File: f.File, Line: f.Line, Repo: f.Repo, Claimed: isClaimed}
			byName[f.Name] = si
			order = append(order, f.Name)
		}
		if si.Kind == "" {
			if sk, ok := f.PropAny(propSymbolKind).(string); ok {
				si.Kind = sk
			}
		}
		if exp, ok := f.PropAny(propExported).(bool); ok && exp {
			si.Exported = true
		}
		if ov, ok := f.PropAny(propOverride).(bool); ok && ov {
			si.Override = true
		}
		if di, ok := f.PropAny(propDIProvider).(bool); ok && di {
			si.DIProvider = true
		}
		if ac, ok := f.PropAny(propAndroidComponent).(string); ok && si.AndroidComponent == "" {
			si.AndroidComponent = ac
		}
		if ic, ok := f.PropAny(propIOSComponent).(string); ok && si.IOSComponent == "" {
			si.IOSComponent = ic
		}
		if wc, ok := f.PropAny(propWebComponent).(string); ok && si.WebComponent == "" {
			si.WebComponent = wc
		}
		if lang, ok := f.PropAny(propLanguage).(string); ok && si.Language == "" {
			si.Language = lang
		}
		if cc, ok := f.PropAny(propCLICommand).(bool); ok && cc {
			si.CLICommand = true
		}
		if fr, ok := f.PropAny(propFrameworkRegistered).(bool); ok && fr {
			si.FrameworkReg = true
		}
		if g, ok := f.PropAny(propGenerated).(bool); ok && g {
			si.Generated = true
		}
		if sc, ok := f.PropAny(propSpringComponent).(string); ok && si.SpringComponent == "" {
			si.SpringComponent = sc
		}
		if da, ok := f.PropAny(propDubboActivate).(bool); ok && da {
			si.DubboActivate = true
		}
		if sp, ok := f.PropAny(propScannedPlugin).(bool); ok && sp {
			si.ScannedPlugin = true
		}
		for _, r := range f.Relations {
			switch {
			case r.Kind == facts.RelDeclares && si.Package == "":
				si.Package = r.Target
			case isUsageKind(r.Kind):
				si.UsageOut = true
				addRef(refSources, r.Target, f.Name)
				if seg := lastSeg(r.Target); seg != r.Target {
					addRef(refSources, seg, f.Name)
				}
				// Fold the constant receiver of a "Foo.bar" call in as a use of Foo,
				// so a class referenced only via a call (e.g. Ruby PostCreator.create)
				// is not mis-reported as an unreferenced orphan.
				for _, recv := range constReceiverRefs(r.Target) {
					addRef(refSources, recv, f.Name)
				}
				// Fold self-qualified dispatch (`self.class.foo`, `cls.foo`) down to
				// the bare method name, so a method reached only via dynamic
				// self-dispatch is not mis-reported as an unreferenced orphan.
				for _, m := range selfReceiverRefs(r.Target) {
					addRef(refSources, m, f.Name)
				}
			}
		}
	}

	syms := make([]symInput, 0, len(order))
	for _, name := range order {
		syms = append(syms, *byName[name])
	}

	// Package facts carry the functions a package's own var and const initializers
	// reference. A dispatch table is usually an unexported package-level var, so it
	// has no symbol of its own and the only honest owner of the edge is the package
	// — see goextractor/funcvalues.go. Without this, every parser reachable only
	// through such a table reads as dead at high confidence. Only usage relations are
	// folded in; a module's `imports` and `declares` say nothing about a symbol.
	for _, f := range store.ByKind(facts.KindModule) {
		for _, r := range f.Relations {
			if !isUsageKind(r.Kind) {
				continue
			}
			addRef(refSources, r.Target, f.Name)
			if seg := lastSeg(r.Target); seg != r.Target {
				addRef(refSources, seg, f.Name)
			}
		}
	}

	// Route facts reference their handler symbol via props["handler"] (e.g.
	// "aiCoachHandler.GetCoachingInsight"). HTTP handlers are registered as method
	// VALUES, so this usage never appears as a "calls" edge — fold it in here so
	// handler methods are not mis-reported as orphans. The route name is the
	// reference source (never equal to a symbol name).
	for _, f := range store.ByKind(facts.KindRoute) {
		h, _ := f.PropAny(propHandler).(string)
		if h == "" {
			continue
		}
		addRef(refSources, h, f.Name)
		if seg := lastSeg(h); seg != h {
			addRef(refSources, seg, f.Name)
		}
	}

	// Test-reference facts (KindTestRef) carry the production symbols a test/spec
	// file exercises. Test files are excluded from normal indexing, so these are
	// the ONLY visible evidence that a symbol is used by a test — fold them in so a
	// production method called only from a spec is not mis-reported as dead. The
	// fact name is the test file path (never equal to a production symbol name), so
	// this introduces no self-reference.
	for _, f := range store.ByKind(facts.KindTestRef) {
		for _, r := range f.Relations {
			if r.Kind != facts.RelCalls {
				continue
			}
			addRef(refSources, r.Target, f.Name)
			if seg := lastSeg(r.Target); seg != r.Target {
				addRef(refSources, seg, f.Name)
			}
			for _, recv := range constReceiverRefs(r.Target) {
				addRef(refSources, recv, f.Name)
			}
			for _, m := range selfReceiverRefs(r.Target) {
				addRef(refSources, m, f.Name)
			}
		}
	}

	// File-reference facts (KindFileRef) carry the production symbols referenced by
	// top-level / file-scope calls that have no enclosing symbol — fixtures
	// (db/fixtures/*.rb doing `Badge.foo`), initializers, and plugin
	// `after_initialize do register_x ... end` blocks. Fold them in exactly like
	// KindTestRef so those methods are not mis-reported as dead. The fact name is the
	// source file path (never equal to a symbol name), so no self-reference arises.
	for _, f := range store.ByKind(facts.KindFileRef) {
		for _, r := range f.Relations {
			if r.Kind != facts.RelCalls {
				continue
			}
			addRef(refSources, r.Target, f.Name)
			if seg := lastSeg(r.Target); seg != r.Target {
				addRef(refSources, seg, f.Name)
			}
			for _, recv := range constReceiverRefs(r.Target) {
				addRef(refSources, recv, f.Name)
			}
			for _, m := range selfReceiverRefs(r.Target) {
				addRef(refSources, m, f.Name)
			}
		}
	}

	// Module facts carry usage edges that have no enclosing symbol — notably C/C++
	// file-scope registration-macro references (module_init(foo), EXPORT_SYMBOL(foo),
	// DEVICE_ATTR(.., show, store)), which the extractor hangs off the directory
	// module fact. Fold those in so the registered entry points are not mis-reported
	// as orphans. The module name (`<dir>`) is the source — never equal to a symbol
	// name (`<dir>.<name>`), so this introduces no self-reference.
	for _, f := range store.ByKind(facts.KindModule) {
		for _, r := range f.Relations {
			if !isUsageKind(r.Kind) {
				continue
			}
			addRef(refSources, r.Target, f.Name)
			if seg := lastSeg(r.Target); seg != r.Target {
				addRef(refSources, seg, f.Name)
			}
			for _, recv := range constReceiverRefs(r.Target) {
				addRef(refSources, recv, f.Name)
			}
			for _, m := range selfReceiverRefs(r.Target) {
				addRef(refSources, m, f.Name)
			}
		}
	}

	// A TYPE whose member is used is used. The graph records a call to
	// `Extensions.AddSecretsManagerServices` as a reference to the METHOD, and
	// nothing ever names the static class that holds it — so the class read as an
	// isolated orphan while its own method was demonstrably called. The same shape
	// covers a controller reached only through its routed action.
	//
	// 578 of bitwarden-server's 1,145 orphan classes (50%) had at least one used
	// member, which made this the largest remaining false-positive bucket after DI
	// registrations were folded into the graph itself.
	//
	// The USER of the member becomes the user of the type, not the member: crediting
	// the member would make every type its own referent and no type could ever be
	// dead.
	foldMemberUseIntoOwner(order, byName, refSources)

	// Python __init__.py re-exports (`from .x import Y`) surface Y as part of the
	// package's public API. Such names are referenced via the package, not by a
	// call edge, so fold them in as references to avoid mis-reporting public
	// re-exported symbols as orphans. The dependency fact name is the source.
	for _, f := range store.ByKind(facts.KindDependency) {
		if names, ok := f.Prop(propReexports); ok {
			for _, n := range toStringSlice(names) {
				addRef(refSources, n, f.Name)
			}
		}
		// Ruby mixins (`include`/`extend`/`prepend M`) emit an `implements` edge
		// on the dependency fact, not on a symbol fact, so the mixed-in module
		// would otherwise look unreferenced. Fold those targets in as uses.
		for _, r := range f.Relations {
			if r.Kind != facts.RelImplements {
				continue
			}
			addRef(refSources, r.Target, f.Name)
			if seg := lastSeg(r.Target); seg != r.Target {
				addRef(refSources, seg, f.Name)
			}
		}
	}

	// Dynamic-dispatch prefixes: an interpolated symbol like `:"report_#{type}"`
	// implies methods named `report_*` are invoked by computed name
	// (public_send/send), which the graph cannot record as a call edge. Treat any
	// function/method whose bare name starts with such a prefix as referenced, so it
	// is not mis-reported as dead. Evidence-based (only fires when such a symbol
	// exists) and additive — it can only hide a real orphan, never invent one.
	var dynPrefixes []string
	for _, f := range store.ByKind(facts.KindFileRef) {
		if raw, ok := f.Prop(propDynamicSendPrefixes); ok {
			dynPrefixes = append(dynPrefixes, toStringSlice(raw)...)
		}
	}
	if len(dynPrefixes) > 0 {
		for i := range syms {
			if syms[i].Kind != facts.SymbolFunc && syms[i].Kind != facts.SymbolMethod {
				continue
			}
			bn := bareName(syms[i].Name)
			for _, p := range dynPrefixes {
				if p != "" && strings.HasPrefix(bn, p) {
					addRef(refSources, bn, "\x00dynamic-dispatch")
					break
				}
			}
		}
	}

	return syms, refSources
}

// addRef records that source references the given candidate name.
func addRef(refSources refIndex, name, source string) {
	refSources.add(name, source)
}

// toStringSlice coerces a fact prop into a []string. Props deserialized from a
// snapshot arrive as []any; in-memory facts may already be []string.
func toStringSlice(v any) []string {
	switch s := v.(type) {
	case []string:
		return s
	case []any:
		out := make([]string, 0, len(s))
		for _, e := range s {
			if str, ok := e.(string); ok && str != "" {
				out = append(out, str)
			}
		}
		return out
	}
	return nil
}

// --- responses ---

type kindCount struct {
	Kind             string `json:"kind"`
	Isolated         int    `json:"isolated"`
	Unreferenced     int    `json:"unreferenced"`
	Exported         int    `json:"exported"`
	HighConfidence   int    `json:"high_confidence"`
	MediumConfidence int    `json:"medium_confidence"`
	Total            int    `json:"total"`
}

type summaryResponse struct {
	// TotalSymbols is the population the orphans were drawn from: symbols that orphan
	// analysis actually considered, under the active filters (see isCandidate). It is
	// the denominator of total_orphans. It used to be every symbol in the snapshot —
	// which both ignored the caller's filters AND counted test/entry-point symbols
	// that can never be orphans, so the dead-code rate it implied was wrong in two
	// directions at once.
	TotalSymbols int `json:"total_symbols"`
	// RepoWideSymbols is the whole snapshot's symbol count, kept for context. It is
	// the ONLY unfiltered number in this response, and it is named so it cannot be
	// mistaken for the denominator.
	RepoWideSymbols int         `json:"repo_wide_symbols"`
	TotalOrphans    int         `json:"total_orphans"`
	Isolated        int         `json:"isolated"`
	Unreferenced    int         `json:"unreferenced"`
	Mode            string      `json:"mode"`
	ByKind          []kindCount `json:"by_kind"`
	Note            string      `json:"note"`
}

type fullResponse struct {
	Orphans  []Orphan `json:"orphans"`
	Total    int      `json:"total"`
	Returned int      `json:"returned"`
	Mode     string   `json:"mode"`
	Note     string   `json:"note"`
}

const responseNote = "References are matched by symbol short-name (the snapshot's call/implements " +
	"edges are unresolved), so detection is conservative: a symbol is treated as used if its name " +
	"matches any reference, avoiding false 'unused' reports at the cost of missing some orphans " +
	"(common names, generated code). CONFIDENCE: 'function' findings are HIGH — plain calls are " +
	"reliably tracked as edges. 'struct'/'class'/'interface' findings are MEDIUM — these are marked " +
	"used via instantiates/injects/implements edges (which ARE tracked), so an unreferenced one is a " +
	"strong dead-code lead, but field/param/return type usage is not edge-tracked so verify before " +
	"removing. 'method'/'type'/'const'/'var' findings are LOW — methods are often reached as method " +
	"values (e.g. HTTP handler registration — partially rescued via route handler metadata), via " +
	"interface dispatch, or by reflection, and plain type/const/var usage is not edge-tracked. Treat " +
	"medium/low findings as leads to verify, not safe deletions. Exported symbols may be consumed " +
	"outside this snapshot. PYTHON: call edges are now emitted for absolute intra-project imports " +
	"(from pkg.mod import fn; fn()), same-module/relative calls, top-level (module-scope) calls, and " +
	"decorator applications, so most functions are edge-tracked — but still treat findings as leads: " +
	"registry/dynamic wiring (provider.yaml, entry_points, importlib-by-name, getattr dispatch) is not " +
	"a call edge. Excluded as entry points / non-app: framework hooks loaded by name (gunicorn hooks, " +
	"ASGI lifespan, Airflow cluster policies), click/Typer CLI commands, decorator-registered handlers " +
	"(FastAPI exception_handler/middleware/on_event, Modal function/local_entrypoint), codegen output " +
	"(files carrying a DO NOT EDIT / generated-by banner), and the docs/, sphinx_exts/, example_dags/, " +
	"migrations/, examples/, evals/, benchmarks/, notebooks/, scripts/ and top-level dev/ (developer tooling) trees; test code (incl. tests_common/test_utils) is excluded " +
	"by default (pass include_tests, or include_entrypoints for CLI/hooks, or package= for a tree). Dunder " +
	"methods and __init__.py re-exports are treated as used; the exported flag follows the leading-" +
	"underscore convention. RUBY: also an UPPER BOUND — Ruby is public-by-default so most " +
	"symbols are 'exported' and the visibility filter is weak; metaprogramming, dynamic dispatch, view " +
	"templates, and resourceful-route controller actions are not call edges. Bare method calls, Rails " +
	"callback/validation symbol references (before_action :x, validate :y), mixin includes, and the " +
	"constant receiver of Foo.bar calls ARE folded in. Rails migrations (db/migrate, db/post_migrate), " +
	"the script/ and vendor/ trees, and `scope :name` model-scope pseudo-symbols are excluded by " +
	"default (they are loaded/dispatched by the framework, never referenced by name); spec/ test trees " +
	"are excluded too. Scope to one of those trees with package= to inspect it. " +
	"SCALA: every symbol inside an object or class is a METHOD, so a Scala repository emits few or no " +
	"high-confidence findings and the actionable tier is class/interface (medium) — filtering " +
	"confidence=high there returns almost nothing and reads as a clean bill of health. Test source sets " +
	"(src/test, src/it, src/multi-jvm) are excluded, with their outbound references folded back in, so a " +
	"symbol exercised only by a spec is not reported. Still NOT tracked, so verify before deleting: a " +
	"type used only in a TYPE position (a DTO named solely as `f[Payload]` or a field type), a bare " +
	"identifier passed as a value (a function reference handed to a callback), and a generic function " +
	"reference (`fsm[IO].apply`). Implicit resolution and extension-method dispatch are not edges. " +
	"C/C++: macros are not " +
	"expanded. Function-pointer wiring IS tracked — struct ops-table initializers (.read = fn), field " +
	"assignments (obj->cb = fn), in-body compound-literal initializers (cfg = (struct X){ .cb = fn }), " +
	"callback args (register(fn)), file-scope registration macros " +
	"(module_init/*_initcall/EXPORT_SYMBOL/module_*_driver/DEVICE_ATTR, incl. qualifier-prefixed " +
	"`static DEFINE_*_PM_OPS(name, suspend, resume)`), function calls or ops-table fields " +
	"(.set = fn) inside #define bodies, attribute/show macros expanded with the repo's own " +
	"#defines (CONFIGFS_ATTR, DEVICE_ATTR_RO/RW/WO incl. the static single-arg form, BUS_ATTR_*, " +
	"SENSOR_DEVICE_ATTR, DEFINE_SHOW_ATTRIBUTE → name##_show/_store), ALL-CAPS `static inline` " +
	"functions called in C, and callbacks in macro-opened structs (MACHINE_START/DT_MACHINE_START ... " +
	"MACHINE_END). Still NOT tracked: macros defined only in external/system headers (not in the analyzed " +
	"tree), conditional (#ifdef) macro variants (the last definition wins), macro invocations nested in an " +
	"array/struct initializer (e.g. an ioctl table), and callbacks wired in a local (in-function) struct/array " +
	"initializer — verify C/C++ findings before deleting."

// summarize builds the per-symbol-type summary from the orphan list.
// summarize aggregates the orphan set. `candidates` is the population the orphans
// were drawn from (post-exclusion, post-filter) and is the denominator; `repoWide` is
// the whole snapshot, carried only as context. The argument order is the contract:
// the scoped number comes first, because that is the one every rate is built on.
func summarize(orphans []Orphan, candidates, repoWide int, mode string) summaryResponse {
	resp := summaryResponse{
		TotalSymbols:    candidates,
		RepoWideSymbols: repoWide,
		TotalOrphans:    len(orphans),
		Mode:            mode,
		Note:            responseNote,
	}
	idx := make(map[string]int)
	for _, o := range orphans {
		if o.Class == classIsolated {
			resp.Isolated++
		} else {
			resp.Unreferenced++
		}
		i, ok := idx[o.Kind]
		if !ok {
			i = len(resp.ByKind)
			idx[o.Kind] = i
			resp.ByKind = append(resp.ByKind, kindCount{Kind: o.Kind})
		}
		kc := &resp.ByKind[i]
		kc.Total++
		if o.Class == classIsolated {
			kc.Isolated++
		} else {
			kc.Unreferenced++
		}
		if o.Exported {
			kc.Exported++
		}
		switch o.Confidence {
		case confHigh:
			kc.HighConfidence++
		case confMedium:
			kc.MediumConfidence++
		}
	}
	sort.SliceStable(resp.ByKind, func(i, j int) bool {
		if resp.ByKind[i].Total != resp.ByKind[j].Total {
			return resp.ByKind[i].Total > resp.ByKind[j].Total
		}
		return resp.ByKind[i].Kind < resp.ByKind[j].Kind
	})
	return resp
}

func renderCompact(orphans []Orphan, mode string) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "Orphan symbols — %d (mode=%s):\n\n", len(orphans), mode)
	sb.WriteString("| Kind | Name | Class | Conf | Location |\n")
	sb.WriteString("|------|------|-------|------|----------|\n")
	for _, o := range orphans {
		loc := o.File
		if o.Line > 0 {
			loc = fmt.Sprintf("%s:%d", o.File, o.Line)
		}
		fmt.Fprintf(&sb, "| %s | %s | %s | %s | %s |\n", o.Kind, o.Name, o.Class, o.Confidence, loc)
	}
	return sb.String()
}

const toolDescription = "Find orphan symbols — dead code that nothing references — directly from the " +
	"loaded snapshot graph (no re-indexing). Run after generate_snapshot. " +
	"An orphan is a symbol that nothing else references; it is class='isolated' when it also " +
	"references nothing, or class='unreferenced' when it still calls others (uncalled-but-calling " +
	"dead code). mode= selects 'both' (default), 'isolated', or 'unreferenced'. " +
	"By default output_mode='summary' returns counts grouped per symbol kind (with isolated/" +
	"unreferenced/exported/high_confidence splits); use output_mode='full' for the per-symbol list " +
	"with file:line cleanup targets, or 'compact' for a markdown table. " +
	"CONFIDENCE: references are matched by short name (the graph's call/implements edges are " +
	"unresolved), so detection is conservative and never flags clearly-used code. Only 'function' " +
	"findings are confidence='high' (plain calls are reliably tracked); 'method' is 'low' (methods " +
	"are reached as values, via interface dispatch, or reflection — route handlers are partially " +
	"rescued via route metadata) and struct/interface/type/const/var are 'low' (type usage is not " +
	"edge-tracked). Filter with confidence='high' for the actionable set; treat 'low' as leads to " +
	"verify, not safe deletions. Exported symbols are included but flagged (may be used outside this " +
	"snapshot); combine confidence='high' with visibility='unexported' for the safest cleanup list. " +
	"Test symbols and entry points (main/init) are excluded by default (include_tests/" +
	"include_entrypoints to keep them). Filter with kind=/package=/repo=. " +
	"For the blast radius of a specific symbol use impact_analysis; for package-level health use " +
	"package_metrics; for graph walks use traverse. " +
	"Pass max_tokens to hard-cap output. High-confidence orphans also surface via " +
	"query_insights(explainer=\"dead-code\")."

// args are the arguments for the find_orphans tool.
type args struct {
	Mode               string `json:"mode,omitempty" jsonschema:"Which orphans to report: 'both' (default) returns every symbol with no incoming references, each tagged class=isolated|unreferenced; 'isolated' = no references in or out; 'unreferenced' = referenced by nobody but still references others (uncalled-but-calling dead code)."`
	Kind               string `json:"kind,omitempty" jsonschema:"Filter to one symbol kind: function, method, struct, interface, type, class, constant, variable. Default: all kinds."`
	Package            string `json:"package,omitempty" jsonschema:"Filter to symbols whose declaring package contains this substring (e.g. 'internal/app')."`
	Repo               string `json:"repo,omitempty" jsonschema:"Filter by repository label (set in multi-repo/append mode, e.g. 'go-service')."`
	Visibility         string `json:"visibility,omitempty" jsonschema:"'all' (default), 'exported' (public API only), or 'unexported' (private symbols only — the safer-to-delete-within-repo set)."`
	Confidence         string `json:"confidence,omitempty" jsonschema:"Filter by detection confidence: '' (all, default), 'high' (functions — incoming calls are reliably tracked), or 'low' (methods/structs/interfaces/types/consts/vars — dispatch and type usage are not edge-tracked, so verify before removal)."`
	IncludeTests       bool   `json:"include_tests,omitempty" jsonschema:"Include symbols in *_test files, Test/Benchmark/Example/Fuzz functions, and test-support packages (mocks/testutils/fixtures). Default false. Note: _test.go files are excluded from the snapshot itself, so test-support code is flagged dead by default because its test callers are invisible — this keeps it out of the cleanup list."`
	IncludeEntrypoints bool   `json:"include_entrypoints,omitempty" jsonschema:"Include runtime entry points (main, init) which have no callers by nature. Default false."`
	OutputMode         string `json:"output_mode,omitempty" jsonschema:"Output format: 'summary' (DEFAULT, counts grouped per symbol kind), 'full' (per-symbol JSON list with file:line), or 'compact' (markdown table)."`
	Limit              int    `json:"limit,omitempty" jsonschema:"Maximum symbols in full/compact output (1-2000). Default 200. Ignored for summary."`
	MaxTokens          int    `json:"max_tokens,omitempty" jsonschema:"Optional hard cap on output size (approx tokens). Default: no cap."`
}

func norm(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

// Register adds the find_orphans tool to the given MCP server. Calls are
// recorded by the OSS value middleware, which is registered once on this shared
// MCP server and so observes the analyzers too.
func Register(srv *mcp.Server, store func() *facts.Store) {
	mcp.AddTool(srv, &mcp.Tool{
		Name:        "find_orphans",
		Description: toolDescription,
	}, func(_ context.Context, _ *mcp.CallToolRequest, in args) (*mcp.CallToolResult, any, error) {
		if store().Count() == 0 {
			return mcputil.ErrorResult("No facts available. Run generate_snapshot first."), nil, nil
		}

		syms, refSources := collect(store())
		opts := options{
			Mode:               norm(in.Mode, "both"),
			Kind:               in.Kind,
			Package:            in.Package,
			Repo:               in.Repo,
			Visibility:         norm(in.Visibility, "all"),
			Confidence:         in.Confidence,
			IncludeTests:       in.IncludeTests,
			IncludeEntrypoints: in.IncludeEntrypoints,
		}
		orphans := classify(syms, refSources, opts)
		sortOrphans(orphans)

		switch mcputil.ResolveOutputMode(in.OutputMode, mcputil.ModeSummary) {
		case mcputil.ModeFull, mcputil.ModeCompact:
			limit := in.Limit
			if limit <= 0 {
				limit = 200
			}
			if limit > 2000 {
				limit = 2000
			}
			total := len(orphans)
			if len(orphans) > limit {
				orphans = orphans[:limit]
			}
			if mcputil.ResolveOutputMode(in.OutputMode, mcputil.ModeSummary) == mcputil.ModeCompact {
				return mcputil.TextResult(mcputil.CapTokens(renderCompact(orphans, opts.Mode), in.MaxTokens, false)), nil, nil
			}
			return mcputil.JSONResultCapped(fullResponse{
				Orphans:  orphans,
				Total:    total,
				Returned: len(orphans),
				Mode:     opts.Mode,
				Note:     responseNote,
			}, in.MaxTokens)
		default:
			return mcputil.JSONResultCapped(
				summarize(orphans, population(syms, opts), len(syms), opts.Mode), in.MaxTokens)
		}
	})
}

// foldMemberUseIntoOwner marks a type as referenced by whoever references one of
// its members. See the call site for why.
func foldMemberUseIntoOwner(order []string, byName map[string]*symInput, refSources refIndex) {
	for _, name := range order {
		m := byName[name]
		if m == nil {
			continue
		}
		dot := strings.LastIndex(name, ".")
		if dot <= 0 {
			continue
		}
		owner := name[:dot]
		o, ok := byName[owner]
		if !ok || !isOwnerTypeKind(o.Kind) {
			continue
		}
		for _, cand := range candidateNames(m.Name, m.Kind) {
			for _, src := range refSources.sources(cand) {
				// External use only. A member referencing its own type, the type
				// referencing itself, or a SIBLING member of the same type, is all
				// internal: a class whose members only call each other is dead as a
				// unit, and crediting the sibling would make it immortal.
				if src == m.Name || src == owner || ownerOf(src) == owner {
					continue
				}
				addRef(refSources, owner, src)
				if seg := lastSeg(owner); seg != owner {
					addRef(refSources, seg, src)
				}
			}
		}
	}
}

// ownerOf returns a symbol's declaring type, or "" when it has none.
func ownerOf(name string) string {
	if dot := strings.LastIndex(name, "."); dot > 0 {
		return name[:dot]
	}
	return ""
}

// isOwnerTypeKind reports whether a kind can OWN members whose use implies its
// own. Deliberately the type kinds only: a method nested under another method is
// a local function, and its use says nothing about the outer one.
func isOwnerTypeKind(kind string) bool {
	switch kind {
	case facts.SymbolClass, facts.SymbolStruct, facts.SymbolInterface, facts.SymbolType:
		return true
	}
	return false
}

// Summary is the dead-code block `enola --explain` prints: the headline counts,
// split by confidence tier and, orthogonally, by class and visibility.
type Summary struct {
	// Total is the number of orphans; Candidates is the population they were drawn
	// from, which is the set the tool actually examines rather than every symbol in
	// the snapshot. Printing the latter as the denominator overstated the rate by
	// counting test and entry-point symbols orphan analysis never looks at.
	Total      int
	Candidates int
	// The confidence tiers partition the set.
	High, Medium, Low int
	// These two pairs re-cut the SAME set rather than adding to it.
	Isolated, Unreferenced int
	Exported               int
}

// Summarize counts orphans over the whole store with the find_orphans tool's own
// defaults (both classes, all kinds and visibility), so the two agree.
func Summarize(store *facts.Store) Summary {
	syms, refSources := collect(store)
	opts := options{Mode: "both", Visibility: "all"}

	s := Summary{Candidates: population(syms, opts)}
	for _, o := range classify(syms, refSources, opts) {
		s.Total++
		if o.Class == classIsolated {
			s.Isolated++
		} else {
			s.Unreferenced++
		}
		switch o.Confidence {
		case confHigh:
			s.High++
		case confMedium:
			s.Medium++
		default:
			s.Low++
		}
		if o.Exported {
			s.Exported++
		}
	}
	return s
}
